"""Add AppSetting

Revision ID: 0b568581f532
Revises: 7f6c21658896
Create Date: 2026-08-27 19:44:18.113497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b568581f532'
down_revision = '7f6c21658896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_settings_app_name'), ['app_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_settings_key'), ['key'], unique=True)

    op.drop_table('list_p4_codes')
    op.drop_table('list_area_of_law')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_area_of_law',
    sa.Column('pid', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('area_of_law', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('list_p4_codes',
    sa.Column('pid', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('cntry_cd', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cntry_desc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rgn_cd', sa.TEXT(), autoincrement=False, nullable=True)
    )
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_settings_key'))
        batch_op.drop_index(batch_op.f('ix_app_settings_app_name'))

    op.drop_table('app_settings')
    # ### end Alembic commands ###
