"""Add VATM Name field

Revision ID: 4c120c1410ac
Revises: 911477b26fdf
Create Date: 2026-08-28 21:52:48.793899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c120c1410ac'
down_revision = '911477b26fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_assignments_to_matter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vatm_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_assignments_to_matter', schema=None) as batch_op:
        batch_op.drop_column('vatm_name')

    # ### end Alembic commands ###
