"""Add primary_line_of_business to matters

Revision ID: 52b346be7d50
Revises: faf19077f7ab
Create Date: 2026-08-29 20:35:46.416473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b346be7d50'
down_revision = 'faf19077f7ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_line_of_business', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matters', schema=None) as batch_op:
        batch_op.drop_column('primary_line_of_business')

    # ### end Alembic commands ###
