"""Add ListRegistry table

Revision ID: 7f6c21658896
Revises: f70c9b8d3e25
Create Date: 2026-08-27 02:24:29.100646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f6c21658896'
down_revision = 'f70c9b8d3e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('table_name', sa.String(length=120), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('list_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_list_registry_table_name'), ['table_name'], unique=True)

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tasks', ['task_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tasks', ['task_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tasks', ['task_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('list_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_list_registry_table_name'))

    op.drop_table('list_registry')
    # ### end Alembic commands ###
