"""Add VATM app model

Revision ID: 911477b26fdf
Revises: 9dac2fcd0c8c
Create Date: 2026-08-28 18:54:01.542443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911477b26fdf'
down_revision = '9dac2fcd0c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_assignments_to_matter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('division_law_firm_panel', sa.String(length=255), nullable=True),
    sa.Column('funding_type', sa.String(length=100), nullable=False),
    sa.Column('vendor_role', sa.String(length=100), nullable=False),
    sa.Column('default_vendor_gl_account_number', sa.String(length=100), nullable=False),
    sa.Column('fee_arrangement_value', sa.String(length=100), nullable=False),
    sa.Column('syndicate_fixed_fee_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('custom_international_panel', sa.Boolean(), nullable=False),
    sa.Column('panel_law_firms_only', sa.Boolean(), nullable=False),
    sa.Column('subcontractor', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_assignments_to_matter')
    # ### end Alembic commands ###
