"""Add Vendor App and related global IDs

Revision ID: 9dac2fcd0c8c
Revises: 3df48a3c22a4
Create Date: 2026-08-28 13:05:04.634914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dac2fcd0c8c'
down_revision = '3df48a3c22a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('vendor_type', sa.String(length=100), nullable=False),
    sa.Column('storm_third_party_id', sa.String(length=100), nullable=True),
    sa.Column('storm_engagement_id_1', sa.String(length=100), nullable=True),
    sa.Column('storm_engagement_id_2', sa.String(length=100), nullable=True),
    sa.Column('tax_status_type', sa.String(length=100), nullable=True),
    sa.Column('currency_code', sa.String(length=50), nullable=True),
    sa.Column('manual_invoices_only', sa.Boolean(), nullable=False),
    sa.Column('discounts_applicable', sa.Boolean(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('relationship_partner_name', sa.String(length=150), nullable=True),
    sa.Column('relationship_partner_email', sa.String(length=255), nullable=True),
    sa.Column('relationship_partner_phone', sa.String(length=50), nullable=True),
    sa.Column('outside_counsel_email', sa.String(length=255), nullable=True),
    sa.Column('billing_contact_1_name', sa.String(length=150), nullable=False),
    sa.Column('billing_contact_1_email', sa.String(length=255), nullable=False),
    sa.Column('billing_contact_1_phone', sa.String(length=50), nullable=True),
    sa.Column('billing_contact_2_name', sa.String(length=150), nullable=True),
    sa.Column('billing_contact_2_email', sa.String(length=255), nullable=True),
    sa.Column('billing_contact_2_phone', sa.String(length=50), nullable=True),
    sa.Column('billing_contact_3_name', sa.String(length=150), nullable=True),
    sa.Column('billing_contact_3_email', sa.String(length=255), nullable=True),
    sa.Column('billing_contact_3_phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'vendors', ['vendor_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'vendors', ['vendor_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'vendors', ['vendor_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vendor_id')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vendor_id')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vendor_id')

    op.drop_table('vendors')
    # ### end Alembic commands ###
