"""Add migrated boolean field

Revision ID: ab35930813a1
Revises: 52b346be7d50
Create Date: 2026-08-30 09:46:39.051390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab35930813a1'
down_revision = '52b346be7d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('migrated', sa.Boolean(), nullable=True))
        batch_op.drop_column('vendor_name')

    with op.batch_alter_table('matters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('migrated', sa.Boolean(), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('migrated', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('migrated', sa.Boolean(), nullable=True))

    with op.batch_alter_table('vendor_assignments_to_matter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('migrated', sa.Boolean(), nullable=True))

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('migrated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('migrated')

    with op.batch_alter_table('vendor_assignments_to_matter', schema=None) as batch_op:
        batch_op.drop_column('migrated')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('migrated')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('migrated')

    with op.batch_alter_table('matters', schema=None) as batch_op:
        batch_op.drop_column('migrated')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_name', sa.VARCHAR(length=160), autoincrement=False, nullable=False))
        batch_op.drop_column('migrated')

    # ### end Alembic commands ###
