"""Add vatm_id to participants, comments, and activities

Revision ID: faf19077f7ab
Revises: 4c120c1410ac
Create Date: 2026-08-28 23:29:31.237059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faf19077f7ab'
down_revision = '4c120c1410ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vatm_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'vendor_assignments_to_matter', ['vatm_id'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vatm_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'vendor_assignments_to_matter', ['vatm_id'], ['id'])

    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vatm_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'vendor_assignments_to_matter', ['vatm_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vatm_id')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vatm_id')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vatm_id')

    # ### end Alembic commands ###
